#!/bin/bash

function display_help() {
    echo "Usage: ai {x}"
    echo "  x: Your prompt."
    echo "Generates a response to your prompt using the Gemini model."
    echo "get your gemini api key from https://aistudio.google.com/app/apikey"
    echo "then run ai --config to set your api key"
    echo ""
    echo "Options:"
    echo "  --config  Update the current configuration (e.g., API key, model)."
    echo "  --update  Update the terminal-copilot to the latest version."
    echo "  --help    Display this help message."
    echo "  -c        Continuous chatting, Coming soon..."
    echo "  -v        Display the version number."
}

function update_config() {
    python3 $HOME/terminal-copilot/setup_config_file.py
    exit 0
}

if [ "$1" == "--config" ]; then
    update_config
    exit 0
fi


function update_terminal_copilot() {
    echo "Updating terminal-copilot..."
    sudo rm -r $HOME/Terminal-Copilot
    cd $HOME
    git clone https://github.com/SR-Hossain/Terminal-Copilot.git
    cp $HOME/terminal-copilot/history.json $HOME/Terminal-Copilot/
    cp $HOME/terminal-copilot/config $HOME/Terminal-Copilot/
    sudo rm -r $HOME/terminal-copilot
    mkdir $HOME/terminal-copilot
    cp $HOME/Terminal-Copilot/* $HOME/terminal-copilot
    cd $HOME/terminal-copilot
    sudo chmod +x final_command.txt
    sudo chmod +x ai
    sudo cp $HOME/terminal-copilot/ai /usr/bin/
    echo "terminal-copilot updated successfully."
    exit 0
}

if [ "$1" == "--update" ]; then
    update_terminal_copilot
    exit 0
fi


function display_version() {
    echo "ai version 1.0"
    echo "Created by: Syed Sazid Hossain Rezvi"
    echo "https://github.com/SR-Hossain\n"
}

if [ "$1" == "-v" ]; then
    display_version
    exit 0
fi

function continuous_chatting() {
    echo "continuous chatting"
}

if [ "$1" == "--help" ]; then
    display_help
    exit 0
fi

if [ "$1" == "-c" ]; then
    continuous_chatting
    exit 0
fi




python3 $HOME/terminal-copilot/main.py "$@"
# if python script fails, exit
if [ $? -ne 0 ]; then
    exit 1
fi


# Full path to the final_command.txt file
file_path=$HOME/terminal-copilot/final_command.txt

# Check if the file exists
if [ ! -f "$file_path" ]; then
    echo "Error: final_command file not found in terminal-copilot: $file_path"
    exit 1
fi


python3 $HOME/terminal-copilot/copy_command.py

echo ""
echo "Command copied to clipboard. Paste it in the terminal to execute."